spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@127.0.0.1:27020/reply-service?authSource=admin
      auto-index-creation: true

  DataSource:
    url: jdbc:mysql://localhost:3306/reply_db
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:10000, localhost:10001, localhost:10002
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/