name: Deploy reply-service from Docker Hub to EC2

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot App
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> .env
          echo "EC2_DB=${{ secrets.EC2_DB }}" >> .env
          echo "EC2_HOST2=${{ secrets.EC2_HOST2 }}" >> .env
          
          echo "EC2_MONGOID=${{ secrets.EC2_MONGOID }}" >> .env
          echo "EC2_MONGOPW=${{ secrets.EC2_MONGOPW }}" >> .env

      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reply-service:latest

      - name: Save PEM file
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > reply-key.pem
          chmod 400 reply-key.pem

      - name: Create target directory on EC2
        run: |
          ssh -i reply-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "mkdir -p /home/${{ secrets.EC2_USER }}/reply-service"

      - name: Copy docker-compose.yml and .env to EC2
        run: |
          sed "s|\${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g" docker-compose.yml > docker-compose.remote.yml

          scp -i reply-key.pem -o StrictHostKeyChecking=no \
          docker-compose.remote.yml .env \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/reply-service/

      - name: Remote Docker Compose Pull & Up
        run: |
          ssh -i reply-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/reply-service
            mv docker-compose.remote.yml docker-compose.yml

            echo "[✔] .env 파일 내용 확인:"
            cat .env || echo ".env 파일이 없습니다!"

            echo "[✔] 기존 컨테이너 종료 및 제거"
            docker compose down || true
            docker rm -f reply-service || true
          
            echo "[✔] 오래된 이미지 정리 (최근 24시간 이내만 보관)"
            docker image prune -a -f --filter "until=24h"

            echo "[✔] 이미지 pull 및 컨테이너 재시작"
            docker compose pull
            docker compose up -d
          EOF